1.2.1 Пример 
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, 
значение элемента с индексом (3,1) и второй столбец. Индексация 
начинается с нуля.

In [6]:
import numpy as np

arr = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])

print("Массив 5x2:")
print(arr)

print("\nЗначение элемента с индексом (3,1):")
print(arr[3, 1])

print("\nВторой столбец массива:")
print(arr[:, 1])


Массив 5x2:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Значение элемента с индексом (3,1):
7

Второй столбец массива:
[1 3 5 7 9]


1.2.2 Пример
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный 
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [7]:
import numpy as np

# 1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
vector_zeros = np.zeros(10)
print("Вектор размера 10, заполненный нулями:", vector_zeros)

# 2. Создать вектор размера 10, заполненный единицами.
vector_ones = np.ones(10)
print("Вектор размера 10, заполненный единицами:", vector_ones)

# 3. Создать вектор размера 10, заполненный заданным числом.
number = 7
vector_custom = np.full(10, number)
print("Вектор размера 10, заполненный числом", number, ":", vector_custom)

# 4. Создать вектор со значениями от 10 до 19.
vector_range = np.arange(10, 20)
print("Вектор со значениями от 10 до 19:", vector_range)


Вектор размера 10, заполненный нулями: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Вектор размера 10, заполненный единицами: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Вектор размера 10, заполненный числом 7 : [7 7 7 7 7 7 7 7 7 7]
Вектор со значениями от 10 до 19: [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум, 
максимум и среднее значение.


In [9]:
import numpy as np

# Создать массив 10x10 со случайными значениями
arr = np.random.rand(10, 10)


# Найти минимум, максимум и среднее значение
minimum = np.min(arr)
maximum = np.max(arr)
mean = np.mean(arr)

print("Минимум: ", minimum)
print("Максимум: ", maximum)
print("Среднее значение: ", mean)


Минимум:  0.049437156818432526
Максимум:  0.9981980000324839
Среднее значение:  0.4975490637005521


1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [1]:
import numpy as np

# Задать матрицу размерности 5 на 5
mat = np.arange(25).reshape(5, 5)
print("Исходная матрица:\n", mat)

# Поменять 2 строки в матрице местами
mat[[1, 3]] = mat[[3, 1]]
print("Матрица после перестановки строк 1 и 3:\n", mat)


Исходная матрица:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица после перестановки строк 1 и 3:
 [[ 0  1  2  3  4]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [20 21 22 23 24]]


1.2.5 Пример
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


In [2]:
import numpy as np

print("0 * np.nan =", 0 * np.nan)
print("np.nan == np.nan =", np.nan == np.nan)
print("np.inf > np.nan =", np.inf > np.nan)
print("np.nan - np.nan =", np.nan - np.nan)
print("0.3 == 3 * 0.1 =", 0.3 == 3 * 0.1)


0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
0.3 == 3 * 0.1 = False


1.2.6 Пример
Отсортировать массив

2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего). 

In [ ]:
import pandas as pd
import numpy as np

# Series из списка Python
my_list = [10, 20, 30, 40, 50]
s1 = pd.Series(my_list)
print("Series из списка Python:\n", s1)

# Series из словаря Python
my_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
s2 = pd.Series(my_dict)
print("\nSeries из словаря Python:\n", s2)

# Series из массива NumPy с метками
my_array = np.array([10, 20, 30, 40, 50])
my_labels = ['a', 'b', 'c', 'd', 'e']
s3 = pd.Series(my_array, index=my_labels)
print("\nSeries из массива NumPy с метками:\n", s3)


2.2.2 Пример
Дано два Series. Напечатать их первые элементы и все элементы после 
третьего (во втором фрейме).


In [10]:
import pandas as pd

# создаем первый Series
s1 = pd.Series([10, 20, 30, 40, 50])

# создаем второй Series
s2 = pd.Series([100, 200, 300, 400, 500], index=['a', 'b', 'c', 'd', 'e'])

# выводим первый элемент каждого Series
print("Первый элемент s1: ", s1[0])
print("Первый элемент s2: ", s2.iloc[0])  # используем метод .iloc для доступа по индексу

# выводим все элементы после третьего во втором Series
print("Элементы s2 после третьего: ", s2[3:])


Первый элемент s1:  10
Первый элемент s2:  100
Элементы s2 после третьего:  d    400
e    500
dtype: int64


2.2.3 Пример
Создайте новый фрейм данных

In [11]:
import pandas as pd

# создаем словарь с данными
data = {'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'age': [25, 32, 18, 47, 22],
        'country': ['USA', 'Canada', 'UK', 'USA', 'Canada']}

# создаем фрейм данных из словаря
df = pd.DataFrame(data)

# выводим фрейм данных
print(df)


      name  age country
0    Alice   25     USA
1      Bob   32  Canada
2  Charlie   18      UK
3    David   47     USA
4    Emily   22  Canada


2.2.4 Пример
Загрузите фрейм данных по ссылке: 
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv

In [12]:
import pandas as pd

# загружаем фрейм данных по ссылке
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
df = pd.read_csv(url)

# выводим первые 5 строк фрейм данных
print(df.head())


                                            Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  


2.2.5 Пример
Пронализировать характеристики фрейма данных.


In [14]:
import pandas as pd

# загружаем фрейм данных по ссылке
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
df = pd.read_csv(url)

# выводим первые 5 строк фрейм данных
print(df.head(2))
print (df.tail(3))
print (df.shape)
print (df.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных

In [16]:
import pandas as pd

# загружаем фрейм данных по ссылке
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
df = pd.read_csv(url)

print (df.iloc[1:4])

                                            Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1  


2.2.7 Пример Требуется отобрать строки фрейма данных на основе некоторого 
условия. Необходимо сформировать новый фрейм данных из пассажиров 
первого класса.

In [18]:
import pandas as pd

# загружаем фрейм данных по ссылке
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
df = pd.read_csv(url)

print(df[df['PClass']=='1st'].head(2))

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1


3.2.1. Пример 
Прошкалируйте числовой признак в диапазон между двумя значениями.


In [19]:
from sklearn.preprocessing import MinMaxScaler

# создаем пример числового признака
feature = np.array([10, 20, 30, 40, 50])

# создаем объект MinMaxScaler и задаем диапазон
scaler = MinMaxScaler(feature_range=(0, 1))

# применяем метод fit_transform для масштабирования признака
scaled_feature = scaler.fit_transform(feature.reshape(-1, 1))

# выводим результат
print(scaled_feature)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


3.2.2. Пример
Задача:
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное 
отклонение 1.

In [21]:
from sklearn.preprocessing import StandardScaler

# создаем пример числового признака
feature = np.array([10, 20, 30, 40, 50])

# создаем объект StandardScaler
scaler = StandardScaler()

# применяем метод fit_transform для преобразования признака
scaled_feature = scaler.fit_transform(feature.reshape(-1, 1))

# выводим результат
print(scaled_feature)
print("mean: ", round(scaled_feature.mean()))
print("standard diversion: ", scaled_feature.std())

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
mean:  0
standard diversion:  0.9999999999999999


3.2.3. Пример
Задача:
Дан фрейм данных 
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы

In [22]:
from sklearn.preprocessing import MinMaxScaler

# создаем пример фрейма данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 'B':[103.02,107.26,110.35,114.23,114.68], 'C':['big','small','big','small','small']})

# создаем объект MinMaxScaler
scaler = MinMaxScaler()

# применяем метод fit_transform для масштабирования числовых столбцов
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])

# выводим результат
print(dfTest)


          A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small


In [9]:
import numpy as np 
arr = np.random.randint(100, size= (3,4))
sortedarr = np.sort(arr)
print (sortedarr)

[[ 6 16 19 68]
 [18 27 30 51]
 [ 8 20 52 59]]


1.3.1 Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.


In [1]:
import numpy as np
chessboard = np.array([[0, 1], [1, 0]])
matrix = np.tile(chessboard, (4, 4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2  Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.


In [4]:
import numpy as np 
arr = np.arange(5).repeat(5).reshape(5,5)
print (arr)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


Создать массив 3x3x3 со случайными значениями.


In [2]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.67119476 0.60022523 0.74410939]
  [0.17011342 0.41469894 0.65481703]
  [0.45773163 0.09027598 0.98469849]]

 [[0.20055468 0.50065808 0.06368191]
  [0.83426799 0.45638746 0.68082978]
  [0.08631327 0.47226374 0.77082478]]

 [[0.18262902 0.38120006 0.30643677]
  [0.10952953 0.00385538 0.21607768]
  [0.28096716 0.88979272 0.58919585]]]


1.3.4 Создать матрицу с 0 внутри, и 1 на границах.

In [3]:
import numpy as np

matrix = np.zeros((5, 5))

matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5  Создайте массив и отсортируйте его по убыванию.

In [2]:
import numpy as np 
arr = np.random.randint(0, 10, (5, 4))
print (arr )
print ("the sorted array in decreasing order: ")
print (np.sort(arr, axis=1, kind = "quicksort")[:, ::-1])

[[2 9 2 6]
 [2 9 5 3]
 [2 3 2 9]
 [5 2 1 5]
 [6 6 5 4]]
the sorted array in decreasing order: 
[[9 6 2 2]
 [9 5 3 2]
 [9 3 2 2]
 [5 5 2 1]
 [6 6 5 4]]


1.3.6 Создайте матрицу, выведите ее форму, размер и размерность.

In [3]:
import numpy as np 
arr = np.array([[1,2,3], [4,5,6]])
print ("array size is " , arr.size)
print ("array dimension is : " , arr.ndim)
print ("array shape is : " , arr.shape)

array size is  6
array dimension is :  2
array shape is :  (2, 3)


2-3-1 
Найдитн евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.


In [4]:
import numpy  as np 
import pandas as pd
def evclid(a, b): 
    result = np.sqrt(np.sum((a-b)**2))
    return result
a = pd.Series([1,2,3])
b = pd.Series([4,5,6])
print ('Расстояние между двумя Series (точками) a и b = ', evclid(a,b))


Расстояние между двумя Series (точками) a и b =  5.196152422706632


2.3.2 Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных

In [10]:

import pandas as pd
file = pd.read_csv('example.csv')
print ('First 5 rows are:\n', file.head())
print ("\n")
print ('Last 5 rows are:\n', file.tail())

First 5 rows are:
    first_name  last_name                     email   gender   age
0        John      Smith      john.smith@gmail.com     Male    25
1        Jane        Doe      jane.doe@hotmail.com   Female    30
2         Bob    Johnson            bobj@gmail.com     Male    40
3       Alice   Williams       awilliams@yahoo.com   Female    35
4     Michael      Brown   michael.brown@gmail.com     Male    45


Last 5 rows are:
    first_name   last_name                    email   gender   age
5       Sarah       Davis   sarahdavis@hotmail.com   Female    28
6       David         Lee       davidlee@gmail.com     Male    50
7       Emily      Wilson   emily.wilson@yahoo.com   Female    32
8       James      Taylor      jtaylor@hotmail.com     Male    27
9   Elizabeth   Hernandez           lizh@yahoo.com   Female    38


2.3.3 => Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [29]:
import pandas as pd
file = pd.read_csv('example.csv')

print ("example 2.2.5:\n") 
print(">>first 2 rows:\n ", file.head(2), '\n')
print(">>Last 2 rows:\n ", file.tail(2), '\n')
print(">>data shape:\n ", file.shape, '\n')
print(">>data describe:\n ", file.describe(), '\n')

print ("example 2.2.5:\n")  
print (">>Selecting rows from 1 to 5:\n ", file.iloc[1:6], '\n')


print ("example 2.2.7:\n") 
print (file[file[' gender']==' Male'])


example 2.2.5:

>>first 2 rows:
     first_name  last_name                  email   gender   age
0        John      Smith   john.smith@gmail.com     Male    25
1        Jane        Doe   jane.doe@hotmail.com   Female    30 

>>Last 2 rows:
     first_name   last_name                 email   gender   age
8       James      Taylor   jtaylor@hotmail.com     Male    27
9   Elizabeth   Hernandez        lizh@yahoo.com   Female    38 

>>data shape:
  (10, 5) 

>>data describe:
               age
count  10.000000
mean   35.000000
std     8.205689
min    25.000000
25%    28.500000
50%    33.500000
75%    39.500000
max    50.000000 

example 2.2.5:

>>Selecting rows from 1 to 5:
     first_name  last_name                     email   gender   age
1        Jane        Doe      jane.doe@hotmail.com   Female    30
2         Bob    Johnson            bobj@gmail.com     Male    40
3       Alice   Williams       awilliams@yahoo.com   Female    35
4     Michael      Brown   michael.brown@gmail.com     

3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [5]:
Стандартное масштабирование (standard scaling) - это метод нормализации данных, при котором среднее значение 
всех значений данных становится равным нулю, а стандартное отклонение - единице. Этот метод используется
для приведения значений разных признаков к одному масштабу, 
что может улучшить производительность моделей машинного обучения.

Мин-макс масштабирование (min-max scaling) - это еще один метод 
нормализации данных. В этом методе значения данных приводятся к диапазону от 0 до 1. 
Этот метод также используется для приведения значений разных признаков к одному масштабу и 
улучшения производительности моделей машинного обучения.

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# загрузить фрейм данных
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

# создать объекты преобразования
scaler1 = MinMaxScaler()
scaler2 = StandardScaler()

# применить нормализацию для первого признака
df['sepal_length_cm_normalized'] = scaler1.fit_transform(df[['sepal_length_cm']])

# применить z-масштабирование для второго признака
df['sepal_width_cm_normalized'] = scaler2.fit_transform(df[['sepal_width_cm']])

# вывести первые 5 строк фрейма данных
print(df.head())




# import pandas as pd 
# from sklearn.preprocessing import MinMaxScaler

# file = pd.read_csv('lasttask.csv') 
# target = file[['petal_length_cm', 'petal_width_cm']]

# scaler = MinMaxScaler()
# target_copy = target.copy()  # create a copy of the selected columns
# target_copy[['petal_length_cm', 'petal_width_cm']] = scaler.fit_transform(target_copy[['petal_length_cm', 'petal_width_cm']])

# print(target_copy)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_normalized  
0                    0.222222                   1.032057  
1                    0.166667                  -0.124958  
2                    0.111111                   0.337848  
3                    0.083333                   0.106445  
4                    0.194444                   1.263460  
